/*
 * Amazon AppIntegrations Service
 * <p>The Amazon AppIntegrations service enables you to configure and reuse connections to external applications.</p> <p>For information about how you can use external applications with Amazon Connect, see <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/crm.html\">Set up pre-built integrations</a> and <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-wisdom.html\">Deliver information to agents using Amazon Connect Wisdom</a> in the <i>Amazon Connect Administrator Guide</i>.</p>
 *
 * The version of the OpenAPI document: 2020-07-29
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import org.openapitools.client.model.CreateDataIntegrationResponseFileConfiguration;
import org.openapitools.client.model.CreateDataIntegrationResponseScheduleConfiguration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateDataIntegrationResponse
 */
public class CreateDataIntegrationResponseTest {
    private final CreateDataIntegrationResponse model = new CreateDataIntegrationResponse();

    /**
     * Model tests for CreateDataIntegrationResponse
     */
    @Test
    public void testCreateDataIntegrationResponse() {
        // TODO: test CreateDataIntegrationResponse
    }

    /**
     * Test the property 'arn'
     */
    @Test
    public void arnTest() {
        // TODO: test arn
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'kmsKey'
     */
    @Test
    public void kmsKeyTest() {
        // TODO: test kmsKey
    }

    /**
     * Test the property 'sourceURI'
     */
    @Test
    public void sourceURITest() {
        // TODO: test sourceURI
    }

    /**
     * Test the property 'scheduleConfiguration'
     */
    @Test
    public void scheduleConfigurationTest() {
        // TODO: test scheduleConfiguration
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'clientToken'
     */
    @Test
    public void clientTokenTest() {
        // TODO: test clientToken
    }

    /**
     * Test the property 'fileConfiguration'
     */
    @Test
    public void fileConfigurationTest() {
        // TODO: test fileConfiguration
    }

    /**
     * Test the property 'objectConfiguration'
     */
    @Test
    public void objectConfigurationTest() {
        // TODO: test objectConfiguration
    }

}
