/*
 * Amazon AppIntegrations Service
 * <p>The Amazon AppIntegrations service enables you to configure and reuse connections to external applications.</p> <p>For information about how you can use external applications with Amazon Connect, see <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/crm.html\">Set up pre-built integrations</a> and <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-wisdom.html\">Deliver information to agents using Amazon Connect Wisdom</a> in the <i>Amazon Connect Administrator Guide</i>.</p>
 *
 * The version of the OpenAPI document: 2020-07-29
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DataIntegrationAssociationSummary
 */
public class DataIntegrationAssociationSummaryTest {
    private final DataIntegrationAssociationSummary model = new DataIntegrationAssociationSummary();

    /**
     * Model tests for DataIntegrationAssociationSummary
     */
    @Test
    public void testDataIntegrationAssociationSummary() {
        // TODO: test DataIntegrationAssociationSummary
    }

    /**
     * Test the property 'dataIntegrationAssociationArn'
     */
    @Test
    public void dataIntegrationAssociationArnTest() {
        // TODO: test dataIntegrationAssociationArn
    }

    /**
     * Test the property 'dataIntegrationArn'
     */
    @Test
    public void dataIntegrationArnTest() {
        // TODO: test dataIntegrationArn
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

}
