/*
 * Amazon AppIntegrations Service
 * <p>The Amazon AppIntegrations service enables you to configure and reuse connections to external applications.</p> <p>For information about how you can use external applications with Amazon Connect, see <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/crm.html\">Set up pre-built integrations</a> and <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-wisdom.html\">Deliver information to agents using Amazon Connect Wisdom</a> in the <i>Amazon Connect Administrator Guide</i>.</p>
 *
 * The version of the OpenAPI document: 2020-07-29
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateEventIntegrationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:31.566517+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateEventIntegrationResponse {
  public static final String SERIALIZED_NAME_EVENT_INTEGRATION_ARN = "EventIntegrationArn";
  @SerializedName(SERIALIZED_NAME_EVENT_INTEGRATION_ARN)
  @javax.annotation.Nullable
  private String eventIntegrationArn;

  public CreateEventIntegrationResponse() {
  }

  public CreateEventIntegrationResponse eventIntegrationArn(@javax.annotation.Nullable String eventIntegrationArn) {
    this.eventIntegrationArn = eventIntegrationArn;
    return this;
  }

  /**
   * Get eventIntegrationArn
   * @return eventIntegrationArn
   */
  @javax.annotation.Nullable
  public String getEventIntegrationArn() {
    return eventIntegrationArn;
  }

  public void setEventIntegrationArn(@javax.annotation.Nullable String eventIntegrationArn) {
    this.eventIntegrationArn = eventIntegrationArn;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateEventIntegrationResponse createEventIntegrationResponse = (CreateEventIntegrationResponse) o;
    return Objects.equals(this.eventIntegrationArn, createEventIntegrationResponse.eventIntegrationArn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventIntegrationArn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateEventIntegrationResponse {\n");
    sb.append("    eventIntegrationArn: ").append(toIndentedString(eventIntegrationArn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("EventIntegrationArn");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateEventIntegrationResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateEventIntegrationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateEventIntegrationResponse is not found in the empty JSON string", CreateEventIntegrationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateEventIntegrationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateEventIntegrationResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `EventIntegrationArn`
      if (jsonObj.get("EventIntegrationArn") != null && !jsonObj.get("EventIntegrationArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("EventIntegrationArn"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateEventIntegrationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateEventIntegrationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateEventIntegrationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateEventIntegrationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateEventIntegrationResponse>() {
           @Override
           public void write(JsonWriter out, CreateEventIntegrationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateEventIntegrationResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateEventIntegrationResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateEventIntegrationResponse
   * @throws IOException if the JSON string is invalid with respect to CreateEventIntegrationResponse
   */
  public static CreateEventIntegrationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateEventIntegrationResponse.class);
  }

  /**
   * Convert an instance of CreateEventIntegrationResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

