/*
 * Amazon AppIntegrations Service
 * <p>The Amazon AppIntegrations service enables you to configure and reuse connections to external applications.</p> <p>For information about how you can use external applications with Amazon Connect, see <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/crm.html\">Set up pre-built integrations</a> and <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-wisdom.html\">Deliver information to agents using Amazon Connect Wisdom</a> in the <i>Amazon Connect Administrator Guide</i>.</p>
 *
 * The version of the OpenAPI document: 2020-07-29
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.CreateDataIntegrationRequestFileConfiguration;
import org.openapitools.client.model.CreateDataIntegrationRequestScheduleConfig;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateDataIntegrationRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:31.566517+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateDataIntegrationRequest {
  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_KMS_KEY = "KmsKey";
  @SerializedName(SERIALIZED_NAME_KMS_KEY)
  @javax.annotation.Nonnull
  private String kmsKey;

  public static final String SERIALIZED_NAME_SOURCE_U_R_I = "SourceURI";
  @SerializedName(SERIALIZED_NAME_SOURCE_U_R_I)
  @javax.annotation.Nonnull
  private String sourceURI;

  public static final String SERIALIZED_NAME_SCHEDULE_CONFIG = "ScheduleConfig";
  @SerializedName(SERIALIZED_NAME_SCHEDULE_CONFIG)
  @javax.annotation.Nonnull
  private CreateDataIntegrationRequestScheduleConfig scheduleConfig;

  public static final String SERIALIZED_NAME_TAGS = "Tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private Map<String, String> tags = new HashMap<>();

  public static final String SERIALIZED_NAME_CLIENT_TOKEN = "ClientToken";
  @SerializedName(SERIALIZED_NAME_CLIENT_TOKEN)
  @javax.annotation.Nullable
  private String clientToken;

  public static final String SERIALIZED_NAME_FILE_CONFIGURATION = "FileConfiguration";
  @SerializedName(SERIALIZED_NAME_FILE_CONFIGURATION)
  @javax.annotation.Nullable
  private CreateDataIntegrationRequestFileConfiguration fileConfiguration;

  public static final String SERIALIZED_NAME_OBJECT_CONFIGURATION = "ObjectConfiguration";
  @SerializedName(SERIALIZED_NAME_OBJECT_CONFIGURATION)
  @javax.annotation.Nullable
  private Map<String, Map<String, List<String>>> objectConfiguration = new HashMap<>();

  public CreateDataIntegrationRequest() {
  }

  public CreateDataIntegrationRequest name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the DataIntegration.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CreateDataIntegrationRequest description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * A description of the DataIntegration.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public CreateDataIntegrationRequest kmsKey(@javax.annotation.Nonnull String kmsKey) {
    this.kmsKey = kmsKey;
    return this;
  }

  /**
   * The KMS key for the DataIntegration.
   * @return kmsKey
   */
  @javax.annotation.Nonnull
  public String getKmsKey() {
    return kmsKey;
  }

  public void setKmsKey(@javax.annotation.Nonnull String kmsKey) {
    this.kmsKey = kmsKey;
  }


  public CreateDataIntegrationRequest sourceURI(@javax.annotation.Nonnull String sourceURI) {
    this.sourceURI = sourceURI;
    return this;
  }

  /**
   * The URI of the data source.
   * @return sourceURI
   */
  @javax.annotation.Nonnull
  public String getSourceURI() {
    return sourceURI;
  }

  public void setSourceURI(@javax.annotation.Nonnull String sourceURI) {
    this.sourceURI = sourceURI;
  }


  public CreateDataIntegrationRequest scheduleConfig(@javax.annotation.Nonnull CreateDataIntegrationRequestScheduleConfig scheduleConfig) {
    this.scheduleConfig = scheduleConfig;
    return this;
  }

  /**
   * Get scheduleConfig
   * @return scheduleConfig
   */
  @javax.annotation.Nonnull
  public CreateDataIntegrationRequestScheduleConfig getScheduleConfig() {
    return scheduleConfig;
  }

  public void setScheduleConfig(@javax.annotation.Nonnull CreateDataIntegrationRequestScheduleConfig scheduleConfig) {
    this.scheduleConfig = scheduleConfig;
  }


  public CreateDataIntegrationRequest tags(@javax.annotation.Nullable Map<String, String> tags) {
    this.tags = tags;
    return this;
  }

  public CreateDataIntegrationRequest putTagsItem(String key, String tagsItem) {
    if (this.tags == null) {
      this.tags = new HashMap<>();
    }
    this.tags.put(key, tagsItem);
    return this;
  }

  /**
   * The tags used to organize, track, or control access for this resource. For example, { \&quot;tags\&quot;: {\&quot;key1\&quot;:\&quot;value1\&quot;, \&quot;key2\&quot;:\&quot;value2\&quot;} }.
   * @return tags
   */
  @javax.annotation.Nullable
  public Map<String, String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable Map<String, String> tags) {
    this.tags = tags;
  }


  public CreateDataIntegrationRequest clientToken(@javax.annotation.Nullable String clientToken) {
    this.clientToken = clientToken;
    return this;
  }

  /**
   * A unique, case-sensitive identifier that you provide to ensure the idempotency of the request. If not provided, the Amazon Web Services SDK populates this field. For more information about idempotency, see &lt;a href&#x3D;\&quot;https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/\&quot;&gt;Making retries safe with idempotent APIs&lt;/a&gt;.
   * @return clientToken
   */
  @javax.annotation.Nullable
  public String getClientToken() {
    return clientToken;
  }

  public void setClientToken(@javax.annotation.Nullable String clientToken) {
    this.clientToken = clientToken;
  }


  public CreateDataIntegrationRequest fileConfiguration(@javax.annotation.Nullable CreateDataIntegrationRequestFileConfiguration fileConfiguration) {
    this.fileConfiguration = fileConfiguration;
    return this;
  }

  /**
   * Get fileConfiguration
   * @return fileConfiguration
   */
  @javax.annotation.Nullable
  public CreateDataIntegrationRequestFileConfiguration getFileConfiguration() {
    return fileConfiguration;
  }

  public void setFileConfiguration(@javax.annotation.Nullable CreateDataIntegrationRequestFileConfiguration fileConfiguration) {
    this.fileConfiguration = fileConfiguration;
  }


  public CreateDataIntegrationRequest objectConfiguration(@javax.annotation.Nullable Map<String, Map<String, List<String>>> objectConfiguration) {
    this.objectConfiguration = objectConfiguration;
    return this;
  }

  public CreateDataIntegrationRequest putObjectConfigurationItem(String key, Map<String, List<String>> objectConfigurationItem) {
    if (this.objectConfiguration == null) {
      this.objectConfiguration = new HashMap<>();
    }
    this.objectConfiguration.put(key, objectConfigurationItem);
    return this;
  }

  /**
   * The configuration for what data should be pulled from the source.
   * @return objectConfiguration
   */
  @javax.annotation.Nullable
  public Map<String, Map<String, List<String>>> getObjectConfiguration() {
    return objectConfiguration;
  }

  public void setObjectConfiguration(@javax.annotation.Nullable Map<String, Map<String, List<String>>> objectConfiguration) {
    this.objectConfiguration = objectConfiguration;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDataIntegrationRequest createDataIntegrationRequest = (CreateDataIntegrationRequest) o;
    return Objects.equals(this.name, createDataIntegrationRequest.name) &&
        Objects.equals(this.description, createDataIntegrationRequest.description) &&
        Objects.equals(this.kmsKey, createDataIntegrationRequest.kmsKey) &&
        Objects.equals(this.sourceURI, createDataIntegrationRequest.sourceURI) &&
        Objects.equals(this.scheduleConfig, createDataIntegrationRequest.scheduleConfig) &&
        Objects.equals(this.tags, createDataIntegrationRequest.tags) &&
        Objects.equals(this.clientToken, createDataIntegrationRequest.clientToken) &&
        Objects.equals(this.fileConfiguration, createDataIntegrationRequest.fileConfiguration) &&
        Objects.equals(this.objectConfiguration, createDataIntegrationRequest.objectConfiguration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, kmsKey, sourceURI, scheduleConfig, tags, clientToken, fileConfiguration, objectConfiguration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDataIntegrationRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    kmsKey: ").append(toIndentedString(kmsKey)).append("\n");
    sb.append("    sourceURI: ").append(toIndentedString(sourceURI)).append("\n");
    sb.append("    scheduleConfig: ").append(toIndentedString(scheduleConfig)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    clientToken: ").append(toIndentedString(clientToken)).append("\n");
    sb.append("    fileConfiguration: ").append(toIndentedString(fileConfiguration)).append("\n");
    sb.append("    objectConfiguration: ").append(toIndentedString(objectConfiguration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Name");
    openapiFields.add("Description");
    openapiFields.add("KmsKey");
    openapiFields.add("SourceURI");
    openapiFields.add("ScheduleConfig");
    openapiFields.add("Tags");
    openapiFields.add("ClientToken");
    openapiFields.add("FileConfiguration");
    openapiFields.add("ObjectConfiguration");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("Name");
    openapiRequiredFields.add("KmsKey");
    openapiRequiredFields.add("SourceURI");
    openapiRequiredFields.add("ScheduleConfig");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateDataIntegrationRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateDataIntegrationRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateDataIntegrationRequest is not found in the empty JSON string", CreateDataIntegrationRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateDataIntegrationRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateDataIntegrationRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateDataIntegrationRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("Name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Name").toString()));
      }
      if ((jsonObj.get("Description") != null && !jsonObj.get("Description").isJsonNull()) && !jsonObj.get("Description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Description").toString()));
      }
      if (!jsonObj.get("KmsKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `KmsKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("KmsKey").toString()));
      }
      if (!jsonObj.get("SourceURI").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `SourceURI` to be a primitive type in the JSON string but got `%s`", jsonObj.get("SourceURI").toString()));
      }
      // validate the required field `ScheduleConfig`
      CreateDataIntegrationRequestScheduleConfig.validateJsonElement(jsonObj.get("ScheduleConfig"));
      if ((jsonObj.get("ClientToken") != null && !jsonObj.get("ClientToken").isJsonNull()) && !jsonObj.get("ClientToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ClientToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ClientToken").toString()));
      }
      // validate the optional field `FileConfiguration`
      if (jsonObj.get("FileConfiguration") != null && !jsonObj.get("FileConfiguration").isJsonNull()) {
        CreateDataIntegrationRequestFileConfiguration.validateJsonElement(jsonObj.get("FileConfiguration"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateDataIntegrationRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateDataIntegrationRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateDataIntegrationRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateDataIntegrationRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateDataIntegrationRequest>() {
           @Override
           public void write(JsonWriter out, CreateDataIntegrationRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateDataIntegrationRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateDataIntegrationRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateDataIntegrationRequest
   * @throws IOException if the JSON string is invalid with respect to CreateDataIntegrationRequest
   */
  public static CreateDataIntegrationRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateDataIntegrationRequest.class);
  }

  /**
   * Convert an instance of CreateDataIntegrationRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

