/*
 * Amazon AppIntegrations Service
 * <p>The Amazon AppIntegrations service enables you to configure and reuse connections to external applications.</p> <p>For information about how you can use external applications with Amazon Connect, see <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/crm.html\">Set up pre-built integrations</a> and <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-wisdom.html\">Deliver information to agents using Amazon Connect Wisdom</a> in the <i>Amazon Connect Administrator Guide</i>.</p>
 *
 * The version of the OpenAPI document: 2020-07-29
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import org.openapitools.client.model.CreateDataIntegrationResponseFileConfiguration;
import org.openapitools.client.model.CreateDataIntegrationResponseScheduleConfiguration;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateDataIntegrationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:31.566517+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateDataIntegrationResponse {
  public static final String SERIALIZED_NAME_ARN = "Arn";
  @SerializedName(SERIALIZED_NAME_ARN)
  @javax.annotation.Nullable
  private String arn;

  public static final String SERIALIZED_NAME_ID = "Id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_KMS_KEY = "KmsKey";
  @SerializedName(SERIALIZED_NAME_KMS_KEY)
  @javax.annotation.Nullable
  private String kmsKey;

  public static final String SERIALIZED_NAME_SOURCE_U_R_I = "SourceURI";
  @SerializedName(SERIALIZED_NAME_SOURCE_U_R_I)
  @javax.annotation.Nullable
  private String sourceURI;

  public static final String SERIALIZED_NAME_SCHEDULE_CONFIGURATION = "ScheduleConfiguration";
  @SerializedName(SERIALIZED_NAME_SCHEDULE_CONFIGURATION)
  @javax.annotation.Nullable
  private CreateDataIntegrationResponseScheduleConfiguration scheduleConfiguration;

  public static final String SERIALIZED_NAME_TAGS = "Tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private Map tags;

  public static final String SERIALIZED_NAME_CLIENT_TOKEN = "ClientToken";
  @SerializedName(SERIALIZED_NAME_CLIENT_TOKEN)
  @javax.annotation.Nullable
  private String clientToken;

  public static final String SERIALIZED_NAME_FILE_CONFIGURATION = "FileConfiguration";
  @SerializedName(SERIALIZED_NAME_FILE_CONFIGURATION)
  @javax.annotation.Nullable
  private CreateDataIntegrationResponseFileConfiguration fileConfiguration;

  public static final String SERIALIZED_NAME_OBJECT_CONFIGURATION = "ObjectConfiguration";
  @SerializedName(SERIALIZED_NAME_OBJECT_CONFIGURATION)
  @javax.annotation.Nullable
  private Map objectConfiguration;

  public CreateDataIntegrationResponse() {
  }

  public CreateDataIntegrationResponse arn(@javax.annotation.Nullable String arn) {
    this.arn = arn;
    return this;
  }

  /**
   * Get arn
   * @return arn
   */
  @javax.annotation.Nullable
  public String getArn() {
    return arn;
  }

  public void setArn(@javax.annotation.Nullable String arn) {
    this.arn = arn;
  }


  public CreateDataIntegrationResponse id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public CreateDataIntegrationResponse name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public CreateDataIntegrationResponse description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public CreateDataIntegrationResponse kmsKey(@javax.annotation.Nullable String kmsKey) {
    this.kmsKey = kmsKey;
    return this;
  }

  /**
   * Get kmsKey
   * @return kmsKey
   */
  @javax.annotation.Nullable
  public String getKmsKey() {
    return kmsKey;
  }

  public void setKmsKey(@javax.annotation.Nullable String kmsKey) {
    this.kmsKey = kmsKey;
  }


  public CreateDataIntegrationResponse sourceURI(@javax.annotation.Nullable String sourceURI) {
    this.sourceURI = sourceURI;
    return this;
  }

  /**
   * Get sourceURI
   * @return sourceURI
   */
  @javax.annotation.Nullable
  public String getSourceURI() {
    return sourceURI;
  }

  public void setSourceURI(@javax.annotation.Nullable String sourceURI) {
    this.sourceURI = sourceURI;
  }


  public CreateDataIntegrationResponse scheduleConfiguration(@javax.annotation.Nullable CreateDataIntegrationResponseScheduleConfiguration scheduleConfiguration) {
    this.scheduleConfiguration = scheduleConfiguration;
    return this;
  }

  /**
   * Get scheduleConfiguration
   * @return scheduleConfiguration
   */
  @javax.annotation.Nullable
  public CreateDataIntegrationResponseScheduleConfiguration getScheduleConfiguration() {
    return scheduleConfiguration;
  }

  public void setScheduleConfiguration(@javax.annotation.Nullable CreateDataIntegrationResponseScheduleConfiguration scheduleConfiguration) {
    this.scheduleConfiguration = scheduleConfiguration;
  }


  public CreateDataIntegrationResponse tags(@javax.annotation.Nullable Map tags) {
    this.tags = tags;
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public Map getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable Map tags) {
    this.tags = tags;
  }


  public CreateDataIntegrationResponse clientToken(@javax.annotation.Nullable String clientToken) {
    this.clientToken = clientToken;
    return this;
  }

  /**
   * Get clientToken
   * @return clientToken
   */
  @javax.annotation.Nullable
  public String getClientToken() {
    return clientToken;
  }

  public void setClientToken(@javax.annotation.Nullable String clientToken) {
    this.clientToken = clientToken;
  }


  public CreateDataIntegrationResponse fileConfiguration(@javax.annotation.Nullable CreateDataIntegrationResponseFileConfiguration fileConfiguration) {
    this.fileConfiguration = fileConfiguration;
    return this;
  }

  /**
   * Get fileConfiguration
   * @return fileConfiguration
   */
  @javax.annotation.Nullable
  public CreateDataIntegrationResponseFileConfiguration getFileConfiguration() {
    return fileConfiguration;
  }

  public void setFileConfiguration(@javax.annotation.Nullable CreateDataIntegrationResponseFileConfiguration fileConfiguration) {
    this.fileConfiguration = fileConfiguration;
  }


  public CreateDataIntegrationResponse objectConfiguration(@javax.annotation.Nullable Map objectConfiguration) {
    this.objectConfiguration = objectConfiguration;
    return this;
  }

  /**
   * Get objectConfiguration
   * @return objectConfiguration
   */
  @javax.annotation.Nullable
  public Map getObjectConfiguration() {
    return objectConfiguration;
  }

  public void setObjectConfiguration(@javax.annotation.Nullable Map objectConfiguration) {
    this.objectConfiguration = objectConfiguration;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDataIntegrationResponse createDataIntegrationResponse = (CreateDataIntegrationResponse) o;
    return Objects.equals(this.arn, createDataIntegrationResponse.arn) &&
        Objects.equals(this.id, createDataIntegrationResponse.id) &&
        Objects.equals(this.name, createDataIntegrationResponse.name) &&
        Objects.equals(this.description, createDataIntegrationResponse.description) &&
        Objects.equals(this.kmsKey, createDataIntegrationResponse.kmsKey) &&
        Objects.equals(this.sourceURI, createDataIntegrationResponse.sourceURI) &&
        Objects.equals(this.scheduleConfiguration, createDataIntegrationResponse.scheduleConfiguration) &&
        Objects.equals(this.tags, createDataIntegrationResponse.tags) &&
        Objects.equals(this.clientToken, createDataIntegrationResponse.clientToken) &&
        Objects.equals(this.fileConfiguration, createDataIntegrationResponse.fileConfiguration) &&
        Objects.equals(this.objectConfiguration, createDataIntegrationResponse.objectConfiguration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arn, id, name, description, kmsKey, sourceURI, scheduleConfiguration, tags, clientToken, fileConfiguration, objectConfiguration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDataIntegrationResponse {\n");
    sb.append("    arn: ").append(toIndentedString(arn)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    kmsKey: ").append(toIndentedString(kmsKey)).append("\n");
    sb.append("    sourceURI: ").append(toIndentedString(sourceURI)).append("\n");
    sb.append("    scheduleConfiguration: ").append(toIndentedString(scheduleConfiguration)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    clientToken: ").append(toIndentedString(clientToken)).append("\n");
    sb.append("    fileConfiguration: ").append(toIndentedString(fileConfiguration)).append("\n");
    sb.append("    objectConfiguration: ").append(toIndentedString(objectConfiguration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Arn");
    openapiFields.add("Id");
    openapiFields.add("Name");
    openapiFields.add("Description");
    openapiFields.add("KmsKey");
    openapiFields.add("SourceURI");
    openapiFields.add("ScheduleConfiguration");
    openapiFields.add("Tags");
    openapiFields.add("ClientToken");
    openapiFields.add("FileConfiguration");
    openapiFields.add("ObjectConfiguration");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateDataIntegrationResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateDataIntegrationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateDataIntegrationResponse is not found in the empty JSON string", CreateDataIntegrationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateDataIntegrationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateDataIntegrationResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `Arn`
      if (jsonObj.get("Arn") != null && !jsonObj.get("Arn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Arn"));
      }
      // validate the optional field `Id`
      if (jsonObj.get("Id") != null && !jsonObj.get("Id").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Id"));
      }
      // validate the optional field `Name`
      if (jsonObj.get("Name") != null && !jsonObj.get("Name").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Name"));
      }
      // validate the optional field `Description`
      if (jsonObj.get("Description") != null && !jsonObj.get("Description").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Description"));
      }
      // validate the optional field `KmsKey`
      if (jsonObj.get("KmsKey") != null && !jsonObj.get("KmsKey").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("KmsKey"));
      }
      // validate the optional field `SourceURI`
      if (jsonObj.get("SourceURI") != null && !jsonObj.get("SourceURI").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("SourceURI"));
      }
      // validate the optional field `ScheduleConfiguration`
      if (jsonObj.get("ScheduleConfiguration") != null && !jsonObj.get("ScheduleConfiguration").isJsonNull()) {
        CreateDataIntegrationResponseScheduleConfiguration.validateJsonElement(jsonObj.get("ScheduleConfiguration"));
      }
      // validate the optional field `Tags`
      if (jsonObj.get("Tags") != null && !jsonObj.get("Tags").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("Tags"));
      }
      // validate the optional field `ClientToken`
      if (jsonObj.get("ClientToken") != null && !jsonObj.get("ClientToken").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ClientToken"));
      }
      // validate the optional field `FileConfiguration`
      if (jsonObj.get("FileConfiguration") != null && !jsonObj.get("FileConfiguration").isJsonNull()) {
        CreateDataIntegrationResponseFileConfiguration.validateJsonElement(jsonObj.get("FileConfiguration"));
      }
      // validate the optional field `ObjectConfiguration`
      if (jsonObj.get("ObjectConfiguration") != null && !jsonObj.get("ObjectConfiguration").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("ObjectConfiguration"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateDataIntegrationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateDataIntegrationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateDataIntegrationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateDataIntegrationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateDataIntegrationResponse>() {
           @Override
           public void write(JsonWriter out, CreateDataIntegrationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateDataIntegrationResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateDataIntegrationResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateDataIntegrationResponse
   * @throws IOException if the JSON string is invalid with respect to CreateDataIntegrationResponse
   */
  public static CreateDataIntegrationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateDataIntegrationResponse.class);
  }

  /**
   * Convert an instance of CreateDataIntegrationResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

