/*
 * Amazon AppIntegrations Service
 * <p>The Amazon AppIntegrations service enables you to configure and reuse connections to external applications.</p> <p>For information about how you can use external applications with Amazon Connect, see <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/crm.html\">Set up pre-built integrations</a> and <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-wisdom.html\">Deliver information to agents using Amazon Connect Wisdom</a> in the <i>Amazon Connect Administrator Guide</i>.</p>
 *
 * The version of the OpenAPI document: 2020-07-29
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * The configuration for what files should be pulled from the source.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:31.566517+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateDataIntegrationRequestFileConfiguration {
  public static final String SERIALIZED_NAME_FOLDERS = "Folders";
  @SerializedName(SERIALIZED_NAME_FOLDERS)
  @javax.annotation.Nullable
  private List folders;

  public static final String SERIALIZED_NAME_FILTERS = "Filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  @javax.annotation.Nullable
  private Map filters;

  public CreateDataIntegrationRequestFileConfiguration() {
  }

  public CreateDataIntegrationRequestFileConfiguration folders(@javax.annotation.Nullable List folders) {
    this.folders = folders;
    return this;
  }

  /**
   * Get folders
   * @return folders
   */
  @javax.annotation.Nullable
  public List getFolders() {
    return folders;
  }

  public void setFolders(@javax.annotation.Nullable List folders) {
    this.folders = folders;
  }


  public CreateDataIntegrationRequestFileConfiguration filters(@javax.annotation.Nullable Map filters) {
    this.filters = filters;
    return this;
  }

  /**
   * Get filters
   * @return filters
   */
  @javax.annotation.Nullable
  public Map getFilters() {
    return filters;
  }

  public void setFilters(@javax.annotation.Nullable Map filters) {
    this.filters = filters;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDataIntegrationRequestFileConfiguration createDataIntegrationRequestFileConfiguration = (CreateDataIntegrationRequestFileConfiguration) o;
    return Objects.equals(this.folders, createDataIntegrationRequestFileConfiguration.folders) &&
        Objects.equals(this.filters, createDataIntegrationRequestFileConfiguration.filters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(folders, filters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDataIntegrationRequestFileConfiguration {\n");
    sb.append("    folders: ").append(toIndentedString(folders)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Folders");
    openapiFields.add("Filters");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateDataIntegrationRequestFileConfiguration
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateDataIntegrationRequestFileConfiguration.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateDataIntegrationRequestFileConfiguration is not found in the empty JSON string", CreateDataIntegrationRequestFileConfiguration.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateDataIntegrationRequestFileConfiguration.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateDataIntegrationRequestFileConfiguration` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `Folders`
      if (jsonObj.get("Folders") != null && !jsonObj.get("Folders").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("Folders"));
      }
      // validate the optional field `Filters`
      if (jsonObj.get("Filters") != null && !jsonObj.get("Filters").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("Filters"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateDataIntegrationRequestFileConfiguration.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateDataIntegrationRequestFileConfiguration' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateDataIntegrationRequestFileConfiguration> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateDataIntegrationRequestFileConfiguration.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateDataIntegrationRequestFileConfiguration>() {
           @Override
           public void write(JsonWriter out, CreateDataIntegrationRequestFileConfiguration value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateDataIntegrationRequestFileConfiguration read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateDataIntegrationRequestFileConfiguration given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateDataIntegrationRequestFileConfiguration
   * @throws IOException if the JSON string is invalid with respect to CreateDataIntegrationRequestFileConfiguration
   */
  public static CreateDataIntegrationRequestFileConfiguration fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateDataIntegrationRequestFileConfiguration.class);
  }

  /**
   * Convert an instance of CreateDataIntegrationRequestFileConfiguration to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

