/*
 * Amazon AppIntegrations Service
 * <p>The Amazon AppIntegrations service enables you to configure and reuse connections to external applications.</p> <p>For information about how you can use external applications with Amazon Connect, see <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/crm.html\">Set up pre-built integrations</a> and <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-wisdom.html\">Deliver information to agents using Amazon Connect Wisdom</a> in the <i>Amazon Connect Administrator Guide</i>.</p>
 *
 * The version of the OpenAPI document: 2020-07-29
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Summary information about the DataIntegration association.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:31.566517+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DataIntegrationAssociationSummary {
  public static final String SERIALIZED_NAME_DATA_INTEGRATION_ASSOCIATION_ARN = "DataIntegrationAssociationArn";
  @SerializedName(SERIALIZED_NAME_DATA_INTEGRATION_ASSOCIATION_ARN)
  @javax.annotation.Nullable
  private String dataIntegrationAssociationArn;

  public static final String SERIALIZED_NAME_DATA_INTEGRATION_ARN = "DataIntegrationArn";
  @SerializedName(SERIALIZED_NAME_DATA_INTEGRATION_ARN)
  @javax.annotation.Nullable
  private String dataIntegrationArn;

  public static final String SERIALIZED_NAME_CLIENT_ID = "ClientId";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  @javax.annotation.Nullable
  private String clientId;

  public DataIntegrationAssociationSummary() {
  }

  public DataIntegrationAssociationSummary dataIntegrationAssociationArn(@javax.annotation.Nullable String dataIntegrationAssociationArn) {
    this.dataIntegrationAssociationArn = dataIntegrationAssociationArn;
    return this;
  }

  /**
   * Get dataIntegrationAssociationArn
   * @return dataIntegrationAssociationArn
   */
  @javax.annotation.Nullable
  public String getDataIntegrationAssociationArn() {
    return dataIntegrationAssociationArn;
  }

  public void setDataIntegrationAssociationArn(@javax.annotation.Nullable String dataIntegrationAssociationArn) {
    this.dataIntegrationAssociationArn = dataIntegrationAssociationArn;
  }


  public DataIntegrationAssociationSummary dataIntegrationArn(@javax.annotation.Nullable String dataIntegrationArn) {
    this.dataIntegrationArn = dataIntegrationArn;
    return this;
  }

  /**
   * Get dataIntegrationArn
   * @return dataIntegrationArn
   */
  @javax.annotation.Nullable
  public String getDataIntegrationArn() {
    return dataIntegrationArn;
  }

  public void setDataIntegrationArn(@javax.annotation.Nullable String dataIntegrationArn) {
    this.dataIntegrationArn = dataIntegrationArn;
  }


  public DataIntegrationAssociationSummary clientId(@javax.annotation.Nullable String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * Get clientId
   * @return clientId
   */
  @javax.annotation.Nullable
  public String getClientId() {
    return clientId;
  }

  public void setClientId(@javax.annotation.Nullable String clientId) {
    this.clientId = clientId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DataIntegrationAssociationSummary dataIntegrationAssociationSummary = (DataIntegrationAssociationSummary) o;
    return Objects.equals(this.dataIntegrationAssociationArn, dataIntegrationAssociationSummary.dataIntegrationAssociationArn) &&
        Objects.equals(this.dataIntegrationArn, dataIntegrationAssociationSummary.dataIntegrationArn) &&
        Objects.equals(this.clientId, dataIntegrationAssociationSummary.clientId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataIntegrationAssociationArn, dataIntegrationArn, clientId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DataIntegrationAssociationSummary {\n");
    sb.append("    dataIntegrationAssociationArn: ").append(toIndentedString(dataIntegrationAssociationArn)).append("\n");
    sb.append("    dataIntegrationArn: ").append(toIndentedString(dataIntegrationArn)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("DataIntegrationAssociationArn");
    openapiFields.add("DataIntegrationArn");
    openapiFields.add("ClientId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DataIntegrationAssociationSummary
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DataIntegrationAssociationSummary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DataIntegrationAssociationSummary is not found in the empty JSON string", DataIntegrationAssociationSummary.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DataIntegrationAssociationSummary.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DataIntegrationAssociationSummary` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `DataIntegrationAssociationArn`
      if (jsonObj.get("DataIntegrationAssociationArn") != null && !jsonObj.get("DataIntegrationAssociationArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("DataIntegrationAssociationArn"));
      }
      // validate the optional field `DataIntegrationArn`
      if (jsonObj.get("DataIntegrationArn") != null && !jsonObj.get("DataIntegrationArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("DataIntegrationArn"));
      }
      // validate the optional field `ClientId`
      if (jsonObj.get("ClientId") != null && !jsonObj.get("ClientId").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ClientId"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DataIntegrationAssociationSummary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DataIntegrationAssociationSummary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DataIntegrationAssociationSummary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DataIntegrationAssociationSummary.class));

       return (TypeAdapter<T>) new TypeAdapter<DataIntegrationAssociationSummary>() {
           @Override
           public void write(JsonWriter out, DataIntegrationAssociationSummary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DataIntegrationAssociationSummary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DataIntegrationAssociationSummary given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DataIntegrationAssociationSummary
   * @throws IOException if the JSON string is invalid with respect to DataIntegrationAssociationSummary
   */
  public static DataIntegrationAssociationSummary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DataIntegrationAssociationSummary.class);
  }

  /**
   * Convert an instance of DataIntegrationAssociationSummary to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

