/*
 * Amazon AppIntegrations Service
 * <p>The Amazon AppIntegrations service enables you to configure and reuse connections to external applications.</p> <p>For information about how you can use external applications with Amazon Connect, see <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/crm.html\">Set up pre-built integrations</a> and <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-wisdom.html\">Deliver information to agents using Amazon Connect Wisdom</a> in the <i>Amazon Connect Administrator Guide</i>.</p>
 *
 * The version of the OpenAPI document: 2020-07-29
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import org.openapitools.client.model.GetEventIntegrationResponseEventFilter;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetEventIntegrationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:31.566517+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class GetEventIntegrationResponse {
  public static final String SERIALIZED_NAME_NAME = "Name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_EVENT_INTEGRATION_ARN = "EventIntegrationArn";
  @SerializedName(SERIALIZED_NAME_EVENT_INTEGRATION_ARN)
  @javax.annotation.Nullable
  private String eventIntegrationArn;

  public static final String SERIALIZED_NAME_EVENT_BRIDGE_BUS = "EventBridgeBus";
  @SerializedName(SERIALIZED_NAME_EVENT_BRIDGE_BUS)
  @javax.annotation.Nullable
  private String eventBridgeBus;

  public static final String SERIALIZED_NAME_EVENT_FILTER = "EventFilter";
  @SerializedName(SERIALIZED_NAME_EVENT_FILTER)
  @javax.annotation.Nullable
  private GetEventIntegrationResponseEventFilter eventFilter;

  public static final String SERIALIZED_NAME_TAGS = "Tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private Map tags;

  public GetEventIntegrationResponse() {
  }

  public GetEventIntegrationResponse name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public GetEventIntegrationResponse description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public GetEventIntegrationResponse eventIntegrationArn(@javax.annotation.Nullable String eventIntegrationArn) {
    this.eventIntegrationArn = eventIntegrationArn;
    return this;
  }

  /**
   * Get eventIntegrationArn
   * @return eventIntegrationArn
   */
  @javax.annotation.Nullable
  public String getEventIntegrationArn() {
    return eventIntegrationArn;
  }

  public void setEventIntegrationArn(@javax.annotation.Nullable String eventIntegrationArn) {
    this.eventIntegrationArn = eventIntegrationArn;
  }


  public GetEventIntegrationResponse eventBridgeBus(@javax.annotation.Nullable String eventBridgeBus) {
    this.eventBridgeBus = eventBridgeBus;
    return this;
  }

  /**
   * Get eventBridgeBus
   * @return eventBridgeBus
   */
  @javax.annotation.Nullable
  public String getEventBridgeBus() {
    return eventBridgeBus;
  }

  public void setEventBridgeBus(@javax.annotation.Nullable String eventBridgeBus) {
    this.eventBridgeBus = eventBridgeBus;
  }


  public GetEventIntegrationResponse eventFilter(@javax.annotation.Nullable GetEventIntegrationResponseEventFilter eventFilter) {
    this.eventFilter = eventFilter;
    return this;
  }

  /**
   * Get eventFilter
   * @return eventFilter
   */
  @javax.annotation.Nullable
  public GetEventIntegrationResponseEventFilter getEventFilter() {
    return eventFilter;
  }

  public void setEventFilter(@javax.annotation.Nullable GetEventIntegrationResponseEventFilter eventFilter) {
    this.eventFilter = eventFilter;
  }


  public GetEventIntegrationResponse tags(@javax.annotation.Nullable Map tags) {
    this.tags = tags;
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public Map getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable Map tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetEventIntegrationResponse getEventIntegrationResponse = (GetEventIntegrationResponse) o;
    return Objects.equals(this.name, getEventIntegrationResponse.name) &&
        Objects.equals(this.description, getEventIntegrationResponse.description) &&
        Objects.equals(this.eventIntegrationArn, getEventIntegrationResponse.eventIntegrationArn) &&
        Objects.equals(this.eventBridgeBus, getEventIntegrationResponse.eventBridgeBus) &&
        Objects.equals(this.eventFilter, getEventIntegrationResponse.eventFilter) &&
        Objects.equals(this.tags, getEventIntegrationResponse.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, eventIntegrationArn, eventBridgeBus, eventFilter, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEventIntegrationResponse {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    eventIntegrationArn: ").append(toIndentedString(eventIntegrationArn)).append("\n");
    sb.append("    eventBridgeBus: ").append(toIndentedString(eventBridgeBus)).append("\n");
    sb.append("    eventFilter: ").append(toIndentedString(eventFilter)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Name");
    openapiFields.add("Description");
    openapiFields.add("EventIntegrationArn");
    openapiFields.add("EventBridgeBus");
    openapiFields.add("EventFilter");
    openapiFields.add("Tags");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetEventIntegrationResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetEventIntegrationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetEventIntegrationResponse is not found in the empty JSON string", GetEventIntegrationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetEventIntegrationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetEventIntegrationResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `Name`
      if (jsonObj.get("Name") != null && !jsonObj.get("Name").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Name"));
      }
      // validate the optional field `Description`
      if (jsonObj.get("Description") != null && !jsonObj.get("Description").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Description"));
      }
      // validate the optional field `EventIntegrationArn`
      if (jsonObj.get("EventIntegrationArn") != null && !jsonObj.get("EventIntegrationArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("EventIntegrationArn"));
      }
      // validate the optional field `EventBridgeBus`
      if (jsonObj.get("EventBridgeBus") != null && !jsonObj.get("EventBridgeBus").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("EventBridgeBus"));
      }
      // validate the optional field `EventFilter`
      if (jsonObj.get("EventFilter") != null && !jsonObj.get("EventFilter").isJsonNull()) {
        GetEventIntegrationResponseEventFilter.validateJsonElement(jsonObj.get("EventFilter"));
      }
      // validate the optional field `Tags`
      if (jsonObj.get("Tags") != null && !jsonObj.get("Tags").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("Tags"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetEventIntegrationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetEventIntegrationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetEventIntegrationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetEventIntegrationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetEventIntegrationResponse>() {
           @Override
           public void write(JsonWriter out, GetEventIntegrationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetEventIntegrationResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetEventIntegrationResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetEventIntegrationResponse
   * @throws IOException if the JSON string is invalid with respect to GetEventIntegrationResponse
   */
  public static GetEventIntegrationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetEventIntegrationResponse.class);
  }

  /**
   * Convert an instance of GetEventIntegrationResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

