/*
 * Amazon AppIntegrations Service
 * <p>The Amazon AppIntegrations service enables you to configure and reuse connections to external applications.</p> <p>For information about how you can use external applications with Amazon Connect, see <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/crm.html\">Set up pre-built integrations</a> and <a href=\"https://docs.aws.amazon.com/connect/latest/adminguide/amazon-connect-wisdom.html\">Deliver information to agents using Amazon Connect Wisdom</a> in the <i>Amazon Connect Administrator Guide</i>.</p>
 *
 * The version of the OpenAPI document: 2020-07-29
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * The name of the data and how often it should be pulled from the source.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:31.566517+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ScheduleConfiguration {
  public static final String SERIALIZED_NAME_FIRST_EXECUTION_FROM = "FirstExecutionFrom";
  @SerializedName(SERIALIZED_NAME_FIRST_EXECUTION_FROM)
  @javax.annotation.Nullable
  private String firstExecutionFrom;

  public static final String SERIALIZED_NAME_OBJECT = "Object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  @javax.annotation.Nullable
  private String _object;

  public static final String SERIALIZED_NAME_SCHEDULE_EXPRESSION = "ScheduleExpression";
  @SerializedName(SERIALIZED_NAME_SCHEDULE_EXPRESSION)
  @javax.annotation.Nonnull
  private String scheduleExpression;

  public ScheduleConfiguration() {
  }

  public ScheduleConfiguration firstExecutionFrom(@javax.annotation.Nullable String firstExecutionFrom) {
    this.firstExecutionFrom = firstExecutionFrom;
    return this;
  }

  /**
   * Get firstExecutionFrom
   * @return firstExecutionFrom
   */
  @javax.annotation.Nullable
  public String getFirstExecutionFrom() {
    return firstExecutionFrom;
  }

  public void setFirstExecutionFrom(@javax.annotation.Nullable String firstExecutionFrom) {
    this.firstExecutionFrom = firstExecutionFrom;
  }


  public ScheduleConfiguration _object(@javax.annotation.Nullable String _object) {
    this._object = _object;
    return this;
  }

  /**
   * Get _object
   * @return _object
   */
  @javax.annotation.Nullable
  public String getObject() {
    return _object;
  }

  public void setObject(@javax.annotation.Nullable String _object) {
    this._object = _object;
  }


  public ScheduleConfiguration scheduleExpression(@javax.annotation.Nonnull String scheduleExpression) {
    this.scheduleExpression = scheduleExpression;
    return this;
  }

  /**
   * Get scheduleExpression
   * @return scheduleExpression
   */
  @javax.annotation.Nonnull
  public String getScheduleExpression() {
    return scheduleExpression;
  }

  public void setScheduleExpression(@javax.annotation.Nonnull String scheduleExpression) {
    this.scheduleExpression = scheduleExpression;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduleConfiguration scheduleConfiguration = (ScheduleConfiguration) o;
    return Objects.equals(this.firstExecutionFrom, scheduleConfiguration.firstExecutionFrom) &&
        Objects.equals(this._object, scheduleConfiguration._object) &&
        Objects.equals(this.scheduleExpression, scheduleConfiguration.scheduleExpression);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstExecutionFrom, _object, scheduleExpression);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduleConfiguration {\n");
    sb.append("    firstExecutionFrom: ").append(toIndentedString(firstExecutionFrom)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("    scheduleExpression: ").append(toIndentedString(scheduleExpression)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("FirstExecutionFrom");
    openapiFields.add("Object");
    openapiFields.add("ScheduleExpression");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ScheduleExpression");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ScheduleConfiguration
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ScheduleConfiguration.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ScheduleConfiguration is not found in the empty JSON string", ScheduleConfiguration.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ScheduleConfiguration.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ScheduleConfiguration` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ScheduleConfiguration.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `FirstExecutionFrom`
      if (jsonObj.get("FirstExecutionFrom") != null && !jsonObj.get("FirstExecutionFrom").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("FirstExecutionFrom"));
      }
      // validate the optional field `Object`
      if (jsonObj.get("Object") != null && !jsonObj.get("Object").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Object"));
      }
      // validate the required field `ScheduleExpression`
      String.validateJsonElement(jsonObj.get("ScheduleExpression"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ScheduleConfiguration.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ScheduleConfiguration' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ScheduleConfiguration> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ScheduleConfiguration.class));

       return (TypeAdapter<T>) new TypeAdapter<ScheduleConfiguration>() {
           @Override
           public void write(JsonWriter out, ScheduleConfiguration value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ScheduleConfiguration read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ScheduleConfiguration given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ScheduleConfiguration
   * @throws IOException if the JSON string is invalid with respect to ScheduleConfiguration
   */
  public static ScheduleConfiguration fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ScheduleConfiguration.class);
  }

  /**
   * Convert an instance of ScheduleConfiguration to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

